GERMAN_TO_ENGLISH_DICT = \
{
"Tisch": "table",
"Herd": "stove",
"Haus": "house",
"Saal": "hall",
"Bett": "bed",
"Wand": "wall",
"Tür": "door",
"Topf": "pot",
"Fisch": "fish",
"Pferd": "horse",
"Maus": "mouse",
"Wal": "whale",
"Schaf": "sheep",
"Kuh": "cow",
"Reh": "deer",
"Wolf": "wolf",
"kehren": "sweep",
"streichen": "paint",
"putzen": "clean",
"wischen": "swipe",
"bauen": "build",
"machen": "make",
"öffnen": "open",
"spülen": "clean",
"scheren": "shear",
"streicheln": "pet",
"nutzen": "use",
"fischen": "fish",
"sichten": "sight",
"melken": "milk",
"jagen": "hunt",
"fangen": "catch",
"Fliese": "tile",
"Liege": "lounger",
"Schale": "bowl",
"Stufe": "step",
"Teppich": "rug",
"Sofa": "sofa",
"Dose": "tin can",
"Blume": "flower",
"Fliege": "fly",
"Ziege": "goat",
"Schabe": "roach",
"Stute": "mare",
"Biene": "bee",
"Lama": "llama",
"Zecke": "tick",
"Zebra": "zebra",
"weglegen": "put away",
"anpassen": "adapt",
"einräumen": "put away",
"betreten": "enter",
"verlegen": "misplace",
"verrücken": "shift",
"zudrehen": "turn off",
"abschneiden": "cut off",
"wegfegen": "sweep away",
"einzäunen": "fence in",
"verscheuchen": "shoo away",
"anbeten": "worship",
"verjagen": "chase away",
"versorgen": "provide for",
"abstreifen": "wipe off",
"anfassen": "touch",
"Vieh": "cattle",
"Schwein": "pig",
"Hahn": "rooster",
"Hund": "dog",
"Hai": "shark",
"Bär": "bear",
"Fuchs": "fox",
"Gans": "goose",
"Knie": "knee",
"Bein": "leg",
"Zahn": "tooth",
"Mund": "mouth",
"Arm": "arm",
"Hand": "hand",
"Kopf": "head",
"Hals": "neck",
"meiden": "avoid",
"retten": "rescue",
"schießen": "shoot",
"sehen": "see",
"treiben": "herd",
"essen": "eat",
"rufen": "shout",
"hören": "hear",
"reiben": "rub",
"recken": "stretch",
"schließen": "close",
"drehen": "turn",
"ziehen": "pull",
"dehnen": "stretch",
"heben": "lift",
"strecken": "stretch",
"Katze": "cat",
"Eber": "boar",
"Made": "maggot",
"Hase": "rabbit",
"Löwe": "lion",
"Affe": "monkey",
"Taube": "pigeon",
"Tiger": "tiger",
"Glatze": "bald head",
"Leber": "liver",
"Wade": "calf",
"Nase": "nose",
"Finger": "finger",
"Zehe": "toe",
"Auge": "eye",
"Rücken": "back",
"verschenken": "give away",
"erlegen": "slay",
"auftischen": "serve",
"erschießen": "shoot",
"behandeln": "treat",
"vertreiben": "expel",
"bewundern": "admire",
"entfernen": "remove",
"verrenken": "sprain",
"erheben": "raise",
"abwischen": "wipe",
"verschließen": "close",
"entnehmen": "take out",
"massieren": "massage",
"anstoßen": "clink glasses",
"rasieren": "shave",
}

ENGLISH_TO_GERMAN_DICT = {en_word: ger_word for ger_word, en_word in GERMAN_TO_ENGLISH_DICT.items()}